### ISSUE TITLE
Codes and Numerical Optimisation 

### ISSUE THREAD

**Issue by prinshul** [ebrahimpichka/awesome-optimization#4]
Hi

Is it possible to add implementation of various optimization methods/algorithms and will you be adding numerical optimisation in this repo?

Thanks.

**Comment by ebrahimpichka** [comment]
Hi, 

I haven't had the time to update the repo for a while but yes I'd like to do that, there are many already existing good implementations on GitHub, and they can be referenced in the `Code Repositories` section of the repo.

And regarding the num. opt. methods, I have not looked for good resources on it.

Also, I'd welcome if you would like to make PR for that as well if you have anything specific in mind.
